# apps/app-service-a.yaml

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: service-a
  namespace: argocd        # ArgoCD가 설치된 네임스페이스

spec:
  project: default         # 기본 프로젝트 사용

  # ✅ Git 정보
  source:
    repoURL: https://github.com/gwanghun-choi/msa-gitops.git
    targetRevision: main   # main 브랜치 기준
    path: k8s/service-a    # 이 디렉터리 안의 manifest.yaml 을 읽는다

  # ✅ 배포 대상(K8s 클러스터 + 네임스페이스)
  destination:
    server: https://kubernetes.default.svc
    namespace: default     # service-a 를 배포할 네임스페이스

  # ✅ 자동 싱크 설정
  syncPolicy:
    automated:
      prune: true          # Git에 없는 리소스는 삭제
      selfHeal: true       # Drift 나면 자동으로 원상 복구
    syncOptions:
      - CreateNamespace=true

