# apps/app-service-b.yaml

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: service-b-dev
  namespace: argocd

spec:
  project: default

  source:
    repoURL: https://github.com/gwanghun-choi/msa-gitops.git
    targetRevision: main
    path: k8s/service-b/overlays/dev

  destination:
    server: https://kubernetes.default.svc
    namespace: msa-dev

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

